### PR TITLE
Partial implementation of the canned responses

### PR DESCRIPTION
**Pull request by lucasabond**
Partial implementation of canned responses. It includes:

https://developers.freshdesk.com/api/#view_canned_response
https://developers.freshdesk.com/api/#view_canned_response_folders
https://developers.freshdesk.com/api/#get_details_of_canned_responses_in_folders

### CODE REVIEW

**Comment by trejjam** [comment]
Thank you for the PR. It looks fine to me.

I would like to ask you to update the related table in Readme:
https://github.com/DaveTCode/FreshdeskApiDotnet#api-coverage and mention there the "Canned response: read-only support"

**Comment by trejjam** [comment]
Also, it's necessary to add the client into the dependency container: https://github.com/DaveTCode/FreshdeskApiDotnet/blob/master/FreshdeskApi.Client/Extensions/IocExtensions.cs

**Comment by lucasabond** [comment]
Hey - I just made those updates. And yes, it is tested and works as expected. I am using it in production already.

**Comment by trejjam** [comment]
Sorry I did not notice that reviews were not available to you (there was submit button :see_no_evil:)

**Comment by lucasabond** [comment]
No problem. Just committed the suggestions.

**Comment by trejjam** [comment]
Thank you for the PR. Released as https://github.com/DaveTCode/FreshdeskApiDotnet/releases/tag/0.13.6

**Pull request merged**
