### PR TITLE
Added support to delete companies and contacts

### PR DESCRIPTION
**Pull request by knippers**
Added support to delete a company and to delete a contact.

### CODE REVIEW

**Comment by trejjam** [comment]
Thanks, it looks good to me.
What do you think to keep soft & hard delete as a separate method? I am not a big fan of bool parameters that changes the behavior of a method.

**Comment by knippers** [comment]
I had a look at the documentation again and see I missed an force option. Will split it in DeleteContactAsync and PermanentlyDeleteContactAsync, last one will have a ContactDeleteRequest class.

**Comment by knippers** [comment]
Ok so the force option on the permanent endpoint does not seem to work. Also it is not used as a body but url parameter. So I left in the force as a bool for PermanentlyDeleteContactAsync and will do further testing. The soft delete followed by hard does delete a contact.

**Comment by trejjam** [comment]
Thank you for the change and contribution

**Pull request merged**
