### PR TITLE
Improve pagination code logic

### PR DESCRIPTION
**Pull request by BarbeRouss**
The pagination method was dealing with multiple pagination style.
Now we have 3 distinct class, 

1. Classic pagination (page=x&per_page=y)
2. List pagination (Single call which should not look for another page)
3. Token based pagination (Search for a token link, and use it for the next call)

This is a **breaking change** for user who does `new PaginationConfiguration()`.
They should instead use the correct `PageBasedPaginationConfiguration`, `ListPaginationConfiguration` or `TokenBasedPaginationConfiguration` depending on the api used.

Invalid usage is now detected at compilation time. `pagingConfiguration.GuardPageBasedPagination();` is no longer required.
This also replace the EPagingMode (Custom paging mode logic can directly be implemented in the related class)

### CODE REVIEW

**Comment by BarbeRouss** [comment]
This PR as successfully tested with the following code: 

```    await using var serviceScope = host.Services.CreateAsyncScope();
    var freshdeskContactClient = serviceScope.ServiceProvider.GetRequiredService<IFreshdeskContactClient>();
    var freshdeskCustomObjectClient = serviceScope.ServiceProvider.GetRequiredService<IFreshdeskCustomObjectClient>();
    var freshdeskCompaniesClient = serviceScope.ServiceProvider.GetRequiredService<IFreshdeskCompaniesClient>();
    var filteredCompanies = await freshdeskCompaniesClient.FilterCompaniesAsync("created_at:>'2017-01-01'", new PageBasedPaginationConfiguration()).ToListAsync();

    var allCompanies = await freshdeskCompaniesClient.ListAllCompaniesAsync().ToListAsync();

    ListAllRecordsRequest request = new();

    await foreach (var record in freshdeskCustomObjectClient.ListAllRecordsAsync<Product>(request, "293142", new TokenBasedPaginationConfiguration(startingToken: null, pageSize: 10)))
    {
        Console.WriteLine($"Found record: {record.DisplayId}");
    }
```

**Comment by trejjam** [comment]
Thanks for the refactoring. It looks nice. I will take a deeper look soon

**Comment by trejjam** [comment]
Hi, I made some changes.

Can you try any method for each pagination style, e.g. with pageSize=1 on a set returning at least two items?
The goal is to verify pagination (the list has pagination through the return header link).

Thank you

**Comment by BarbeRouss** [comment]
The `nextLinkHeader` was not absolute for the token base pagination.
I moved the specific logic into each pagination class.

Now, all the pagination works, even the list pagination (I didn't know we had the next link header for that one)
I did verify with a list of 34 companies

**Comment by trejjam** [comment]
Thanks, the `GetPagedResults` looks way clearer now :tada:.

Merging, thank you for the PR

**Pull request merged**
