### PR TITLE
#200 Ticket with custom fields and attachments

### PR DESCRIPTION
**Pull request by IanCodeAces**
A workaround to allow users to create new tickets that contains both custom fields and attachments. The MultipartSerializer used cannot handle the custom fields and produces output that isn't consistent with what Freshdesk expects to receive. As a workaround, we strip out custom fields from the original payload and serialize ticket with attachments without CF and then manually add them back into the MultiPartFormDataContent we are going to send to Freshdesk

Changes:

1. Added new model for CreateTicketRequestWithoutCustomFields (mapped from original request and processed by serializer for attachments)

2. Added static HttpRequestMessageExtensions to seperate logic for building the message

2. Updated FreshdeskHttpClient to use new extensions and produce output

### CODE REVIEW

**Comment by trejjam** [comment]
Hi, thank you for checking `MultipartSerializer` and kicking off the PR.

May I ask you to check if the current implementation still works as expected? (I do not have an FD license anymore)

**Comment by trejjam** [comment]
Fixes #200

**Comment by IanCodeAces** [comment]
> Hi, thank you for checking `MultipartSerializer` and kicking off the PR.
> 
> May I ask you to check if the current implementation still works as expected? (I do not have an FD license anymore)

Hi, yes, I have been submitting forms to our Freshdesk instance with custom fields and attachments yesterday evening and today with no issues at all!

**Comment by trejjam** [comment]
I made some changes, you may find them here: https://github.com/IanCodeAces/FreshdeskApiDotnet/commits/fix/200-customfields-with-attachments Can you test it with this version?

**Comment by IanCodeAces** [comment]
> I made some changes, you may find them here: https://github.com/IanCodeAces/FreshdeskApiDotnet/commits/fix/200-customfields-with-attachments Can you test it with this version?

Hi @trejjam - I can confirm these changes work perfectly so should be good to merge.

Thanks

**Pull request merged**
